version: "3.9"
services:
  db:
    image: postgres:12.3
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.2.1-alpine
    restart: always
    container_name: redis
  backend:
    build: ./backend/core
    ports:
      - "3100:3100"
    depends_on:
      - db
      - redis
  partners:
    build: ./sites/partners
    ports:
      - "3001:3001"
    depends_on:
      - backend
  public:
    build: ./sites/public
    ports:
      - "3000:3000"
    depends_on: 
      - backend