version: "3.7"
services:
  db:
    image: postgres:12.3
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - server-side
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.1-alpine
    restart: always
    container_name: redis
    networks:
      - server-side
    ports:
      - 6379:6379
  backend:
    build: ./backend/core
    ports:
      - "3100:3100"
    networks:
      - server-side
      - client-side
    links:
      - db:db
      - redis:redis
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:password@db/bloom
    volumes:
      - ./backend/core/src:/app/src
    depends_on:
      - db
      - redis
  ui-components:
    build: ./ui-components
  partners:
    build: ./sites/partners
    ports:
      - "3001:3001"
    volumes:
      - ./sites/partners:/app
    networks:
      - client-side
    links:
      - backend
    depends_on:
      - ui-components
      - backend
  public:
    build: ./sites/public
    ports:
      - "3000:3000"
    volumes:
      - ./sites/public:/app
      - ./ui-components:/app/ui-components
    networks:
      - client-side
    links:
      - backend
    depends_on:
      - ui-components
      - backend
networks:
  client-side: {}
  server-side: {}
volumes:
  db-data: