version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0

executors:
  standard-node:
    docker:
      - image: "cimg/node:12.18.4"
      - image: "circleci/postgres:12.3-postgis"
        environment:
          POSTGRES_USER: bloom-ci
          # Never do this in production or with any sensitive / non-test data:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: bloom
  cypress-node:
    docker:
      - image: "cypress/base:12.18.2"
      - image: "circleci/postgres:12.3-postgis"
        environment:
          POSTGRES_USER: bloom-ci
          # Never do this in production or with any sensitive / non-test data:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: bloom

jobs:
  setup:
    executor: standard-node
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/
  setup-with-db:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:backend:core:dbsetup
  lint:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint
  jest-ui-components:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:shared:ui
  jest-backend:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: DB Setup + Backend Core Tests
          command: |
            yarn test:backend:core:dbsetup
            yarn test:backend:core
            yarn test:e2e:backend:core
          environment:
            APP_SECRET: "CI-LONG-SECRET-KEY"
            # DB URL for migration and seeds:
            DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom"
            # DB URL for the jest tests per ormconfig.test.ts
            TEST_DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom"
  build-public:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build:app:public
  build-partners:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build:app:partners
  cypress/run:
    executor: cypress-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Start app in the background
          command: yarn dev:all
          background: true
      - run:
          name: wait for localhost to load
          command: yarn wait-on http://localhost:3000
      - run:
          name: Running Cypress tests
          command: yarn test:app:public
      - store_artifacts:
          path: temp/screenshots

workflows:
  version: 2
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - jest-ui-components:
          requires:
            - setup
      - jest-backend:
          requires:
            - setup
      - build-public:
          requires:
            - setup
      - build-partners:
          requires:
            - setup
      - cypress/run:
          requires:
            - setup
