[build]

command = "yarn run build"
ignore = "/bin/false"

[build.environment]

NODE_VERSION = "12.18.4"
YARN_VERSION = "1.22.4"
NEXT_TELEMETRY_DISABLED = "1"

# reminder: URLs and fragments should *not* have a trailing /
LISTINGS_QUERY = "/listings"